Feat: Support for the group ping feature
Yes-Theory-Fam/database pull request #28
Opened 2021-07-24 12:12 UTC by hasanlatch007

Added Enum for the settings options and added `GroupPingOptions` column for new feat

2021-07-26 10:12 UTC, hasanlatch007 commented
If this is good to go dont merge it till i delete the function michel added for the group YesTheoryUploaded

2021-07-30 14:09 UTC, geisterfurz007 requested changes
Schema changes LGTM!

Please generate the migration (`yarn prisma migrate dev`) and bump the package version (`npm version minor`) and commit both onto this branch as well :)

2021-07-30 14:16 UTC, geisterfurz007 requested changes

2021-07-30 14:16 UTC, geisterfurz007 commented on prisma/schema.prisma
> +  groupPingOption                 GroupPingSetting                  @default(MEMBER)
```suggestion
  groupPingSetting                GroupPingSetting                  @default(MEMBER)
```

2021-07-31 12:17 UTC, hasanlatch007 commented
Ignore the multiple version commits my console lagged and it was doing nothing and suddenly all synced the current one is the last commit

2021-07-31 13:05 UTC, geisterfurz007 approved these changes

2021-07-31 13:05 UTC, merged